services:
  db:
    image: postgres:alpine
    container_name: server-db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  server:
    build: .
    container_name: server
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      - DB_CONNECTION_STRING=postgres://postgres:postgres@db:5432/postgres?sslmode=disable
      - TOKEN_KEY=my_secret_key
      - REFRESH_TOKEN_KEY=my_secret_refresh_key
      - TOKEN_DURATION_SEC=600 # 10 mins
      - REFRESH_TOKEN_SEC=86400 # 1 day
      - GIN_MODE=release
      - ALLOW_ORIGINS=*
      - ALLOW_METHODS=GET,POST,PATCH,DELETE,OPTIONS
      - ALLOW_HEADERS=*
      - EXPOSE_HEADERS=Content-Length
      - MAX_AGE=120
      - CERT_FILE=
      - KEY_FILE=
    volumes:
      - ./certs:/certs
