name: buon18-system
services:
  db:
    image: postgres:alpine
    container_name: buon18-system-database
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
  valkey:
    image: valkey/valkey:8.0-alpine
    container_name: buon18-system-valkey
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./valkey/data:/data
      - ./valkey/valkey.conf:/etc/valkey/valkey.conf
    command: ["valkey-server", "/etc/valkey/valkey.conf"]
  server:
    image: buon18/system-server:2.0.0-a.1
    container_name: buon18-system-server
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      - DB_CONNECTION_STRING=postgres://postgres:postgres@db:5432/postgres?sslmode=disable
      - TOKEN_KEY=my_secret_key
      - REFRESH_TOKEN_KEY=my_secret_refresh_key
      - TOKEN_DURATION_SEC=600 # 10 mins
      - REFRESH_TOKEN_SEC=86400 # 1 day
      - GIN_MODE=release
      - ALLOW_ORIGINS=*
      - ALLOW_METHODS=GET,POST,PATCH,DELETE,OPTIONS
      - ALLOW_HEADERS=*
      - EXPOSE_HEADERS=Content-Length
      - MAX_AGE=120
      - CERT_FILE=
      - KEY_FILE=
    volumes:
      - ./certs:/certs
