version: "3"
services:
  db:
    image: postgres:alpine
    container_name: server-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  server:
    build: .
    container_name: server
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_CONNECTION_STRING: postgres://postgres:postgres@db:5432/postgres?sslmode=disable
      TOKEN_KEY: my_secret_key
      REFRESH_TOKEN_KEY: my_secret_refresh_key
      TOKEN_DURATION_SEC: 60
      REFRESH_TOKEN_SEC: 600
      GIN_MODE: release
      ALLOW_ORIGINS: "*"
      ALLOW_METHODS: GET,POST,PATCH,DELETE,OPTIONS
      ALLOW_HEADERS: "*"
      EXPOSE_HEADERS: Content-Length
      MAX_AGE: 120
