CREATE TYPE user_typ AS ENUM ('User', 'Sys');
CREATE TYPE user_role AS ENUM ('Admin', 'Editor', 'User');

CREATE TABLE "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

    -- Personal information
    name VARCHAR(64) NOT NULL,
    email VARCHAR(64) NOT NULL UNIQUE,

    -- Auth
    pwd VARCHAR(256),

    -- Flags
    typ user_typ NOT NULL DEFAULT 'User',
    role user_role NOT NULL DEFAULT 'User',

    -- Timestamps
    cid bigint NOT NULL,
    ctime timestamp with time zone NOT NULL,
    mid bigint NOT NULL,
    mtime timestamp with time zone NOT NULL  
);