CREATE TYPE user_typ AS ENUM ('User', 'Sys');

CREATE TABLE "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

    -- Personal information
    email VARCHAR(64) NOT NULL,

    -- Auth
    pwd VARCHAR(256),

    -- Flags
    typ user_typ NOT NULL DEFAULT 'User',

    -- Timestamps
    cid bigint NOT NULL,
    ctime timestamp with time zone NOT NULL,
    mid bigint NOT NULL,
    mtime timestamp with time zone NOT NULL  
);