package database

type PQ_KEY_CONSTRAINTS int

const (
	DUPLICATE PQ_KEY_CONSTRAINTS = iota
	NOT_FOUND
)

var PQ_ERROR_CODES = map[PQ_KEY_CONSTRAINTS]string{
	DUPLICATE: "23505",
	NOT_FOUND: "23503",
}
